### ISSUE TITLE
没有 ./clash -d . 这个可执行程序啊

### ISSUE THREAD

**Issue by fuxiaolang** [ghostxu97/clash-for-linux#10]

**Comment by GavindotYang** [comment]
+1

**Comment by ghostxu97** [comment]
这些步骤执行了吗？
[root@localhost ~]# su
[root@localhost ~]# mkdir /opt/clash
[root@localhost ~]# mv Desktop/clash-linux-amd64 /opt/clash/clash
[root@localhost ~]# cd /opt/clash/
