### ISSUE TITLE
请问./clash -d .不是一个可执行程序是怎么回事呢

### ISSUE THREAD

**Issue by yyxisgreat** [ghostxu97/clash-for-linux#12]
(venv) (base) luoxu@rede-3090:/opt/clash$  ./clash -d .
bash: ./clash: cannot execute binary file: Exec format error

**Comment by superzxl114514** [comment]
我也遇到了这个问题，是不是你是用tar -zxvf解压的文件。我改成用gunzip解压就解决了

**Comment by yyxisgreat** [comment]
谢谢你，好像是这样，但是我又遇到了新的问题 FATA[0000] Parse config error: yaml: line 2: mapping values are not allowed in this context，请问有大佬知道吗

**Comment by gyf6666** [comment]
![image](https://github.com/ghostxu97/clash-for-linux/assets/148872612/e63e6b7f-8ce5-4d66-8b54-ff98eb308bb3)
一直卡在这没反应什么情况

**Comment by Amber-siley** [comment]
```./clash -d``` 后面给的是配置文件目录，包括.mmdb和.yaml文件，也就是“工作目录”的意思
按照他的教程你可以```./clash -d /opt/clash```

**Comment by assist726** [comment]
源文件是个gz， 需要 gzip -d file.gz 然后再mv 他忘记说了
