### ISSUE TITLE
没反应

### ISSUE THREAD

**Issue by gyf6666** [ghostxu97/clash-for-linux#13]
![image](https://github.com/ghostxu97/clash-for-linux/assets/148872612/efa9895e-2e75-4d6f-9737-e160375a872f)
一直卡在这没反应

**Comment by ghostxu97** [comment]
这不是没反应，这是表示程序开起来了，你想要后台运行的话就照着文档里面注册成服务去启动。


在 2024年3月19日 ***@***.***> 写道：


image.png (view on web)
 一直卡在这没反应

**Comment by gyf6666** [comment]
我还有一个问题，我的config.yaml是通过wegt方式获得的，里面都是一大堆字符串，在启动clash的时候报错：Parse config error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `dHJvamF...` into config.RawConfig 
如果config.yaml变为正常的键值对格式（window下的原配置文件直接复制过来的）的话，不报错，但是显示以下信息：
INFO[0000] Start initial compatible provider 一元机场       
INFO[0000] Start initial compatible provider 故障转移       
INFO[0000] Start initial compatible provider 自动选择       
INFO[0000] inbound mixed://:7890 create success.        
INFO[0000] RESTful API listening at: 127.0.0.1:9090
与原信息不符；
INFO[0000] Start initial compatible provider Proxy      
INFO[0000] Start initial compatible provider Domestic   
INFO[0000] Start initial compatible provider AsianTV    
INFO[0000] Start initial compatible provider Others     
INFO[0000] Start initial compatible provider GlobalTV；
我该怎么办呢

**Comment by gyf6666** [comment]
我这边clash服务能正常启动，但是网页端的clash显示为空
![image](https://github.com/ghostxu97/clash-for-linux/assets/148872612/b69ec3b2-ae85-4ac7-87a2-f12866b6fc67)

**Comment by ghostxu97** [comment]
按照你订阅的机场服务商教程更新config.yaml文件
