### ISSUE TITLE
wget: unable to resolve host address ‘www.sub-speeder.com’

### ISSUE THREAD

**Issue by puke3615** [ghostxu97/clash-for-linux#16]
$ sudo wget -O Country.mmdb https://www.sub-speeder.com/client-download/Country.mmdb
--2024-05-15 22:13:41--  https://www.sub-speeder.com/client-download/Country.mmdb
Resolving www.sub-speeder.com (www.sub-speeder.com)... failed: Name or service not known.
wget: unable to resolve host address ‘www.sub-speeder.com’

it looks like the host "www.sub-speeder.com" is closed.

**Comment by smallzhong** [comment]
same

**Comment by hstxmgzY** [comment]
same, too

**Comment by godblessbb** [comment]
可以去 github 上找一下镜像源，把链接换上去就可以了https://github.com/Dreamacro/maxmind-geoip/releases/download/20240512/Country.mmdb

**Comment by Cupcc** [comment]
国内CDN加速 https://cdn.jsdelivr.net/gh/Hackl0us/GeoIP2-CN@release/Country.mmdb

**Comment by ghostxu97** [comment]
感谢各位大佬回复补充
