### ISSUE TITLE
config.yaml 加载报错

### ISSUE THREAD

**Issue by WoyouWoyou** [ghostxu97/clash-for-linux#19]
[root@ecs-v100 clash]# ./clash -d .
FATA[0000] Parse config error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `c3M6Ly9...` into config.RawConfig

这个问题如何解决呀。搞不定，找了很多教程了。

**Comment by ghostxu97** [comment]
你的yaml配置文件格式不正确
