### ISSUE TITLE
github上的clash for linux找不到了

### ISSUE THREAD

**Issue by quangWHU** [ghostxu97/clash-for-linux#2]
您好，github上的clash for linux找不到了，您能发送我一份吗？我的邮箱是203149462@qq.com

**Comment by 1770460850** [comment]
+1，感谢。
a1770460850@gmail.com

**Comment by quangWHU** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ghostxu97/clash-for-linux"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 上午8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ghostxu97/clash-for-linux] github上的clash for linux找不到了 (Issue #2)





 
+1，感谢。
 ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Clash.for.Windows-0.20.39-x64-linux.tar.gz (106.30M, 2023年12月08日 09:05 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=3e653130a4153ecdf7b52a3c1f39571b191155010e0f52564c0608010c14070c54031c5308015d19500303035d08010751550007391365770d044258175f0a464f32585e5d5612474c551f020917560d4c1d070414550c5a141d1f44584b4b531b650c&code=ae1099e4

**Comment by xubingod** [comment]
也方便发我一份吗？348856485@qq.com   万分感谢

**Comment by lebron-2016** [comment]
您好，方便发我一份吗？xiaozh0919@gmail.com 万分感谢！！

**Comment by wanttosleepnow** [comment]
你好，可以方便再发一份吗，上边的文件过期了，xxishappy@gmail.com

**Comment by ivorysillegals** [comment]
你好，我也是来要文件的，可以再发一次吗？谢谢！czczc66@gmail.com

**Comment by ghostxu97** [comment]
大家可以点击文末Speeder的邀请链接，注册后在他们官网的下载教程栏下载clash for linux哈

**Comment by capeapp** [comment]
您好，github上的clash for linux找不到了，您能发送我一份吗？我的邮箱是zhaogenxin@gmail.com

**Comment by liutao14** [comment]
你好，可以发我一份吗？谢谢liutao14@njust.edu.cn

**Comment by YuehuiWan** [comment]
您好，您能发送我一份吗？我的邮箱是1962591685@qq.com

**Comment by Gavintofd** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ghostxu97/clash-for-linux" ***@***.***&gt;; 发送时间:&nbsp;2023年11月8日(星期三) 上午8:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ghostxu97/clash-for-linux] github上的clash for linux找不到了 (Issue #2) +1，感谢。 ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 Clash.for.Windows-0.20.39-x64-linux.tar.gz (106.30M, 2023年12月08日 09:05 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=3e653130a4153ecdf7b52a3c1f39571b191155010e0f52564c0608010c14070c54031c5308015d19500303035d08010751550007391365770d044258175f0a464f32585e5d5612474c551f020917560d4c1d070414550c5a141d1f44584b4b531b650c&code=ae1099e4

大佬能发我一份吗，这个链接失效了 我的邮箱是1353705035@qq.com  ,非常感谢大佬！！
