### ISSUE TITLE
命令行启动代理报错。。。

### ISSUE THREAD

**Issue by EvanSong77** [ghostxu97/clash-for-linux#8]
没有GUI！云服务器
root@karman-System:/home/codewen# gsettings set org.gnome.system.proxy mode 'manual'

(process:147634): dconf-WARNING **: 21:26:36.143: failed to commit changes to dconf: 无法连接： 没有那个文件或目录

**Comment by ghostxu97** [comment]
参考下这个方式export环境变量试试https://www.cnblogs.com/tany-g/p/17783416.html
